[build]
  command = "cd front-end && npm install && npm run build"
  publish = "front-end/dist"

[context.production.environment]
  VITE_API_URL = "https://sian-d-acqui.onrender.com/api"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
