services:
  # Backend NestJS
  - type: web
    name: sian-dacqui-backend
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install --prefix sian-dacqui-backend && npm run build --prefix sian-dacqui-backend
    startCommand: cd sian-dacqui-backend && npm run start:prod
    healthCheckPath: /api/pizzas
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: sian-dacqui-db
          property: connectionString
      - key: NETLIFY_DATABASE_URL_UNPOOLED
        fromDatabase:
          name: sian-dacqui-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: DB_SYNCHRONIZE
        value: true

databases:
  - name: sian-dacqui-db
    plan: free
    databaseName: sian_dacqui
    user: sian_user
